# Generated by Django 2.1.5 on 2022-03-11 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'Administrator',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoes_name', models.CharField(max_length=64)),
                ('shoes_colour', models.CharField(max_length=16)),
                ('shoes_quantity', models.IntegerField(default=1)),
                ('shoes_size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('outlet', models.DecimalField(decimal_places=2, max_digits=16)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('delivery', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Basket',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_number', models.IntegerField(default=0, unique=True)),
                ('user_name', models.CharField(max_length=64)),
                ('content', models.TextField(blank=True)),
                ('reply', models.TextField(blank=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ID', models.IntegerField(default=0, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('find_address', models.CharField(max_length=512)),
                ('phone_number', models.CharField(max_length=16)),
                ('delivery_options', models.CharField(max_length=16)),
                ('card_number', models.IntegerField(default=0)),
                ('expiration_date', models.IntegerField(default=0)),
                ('security_code', models.IntegerField(default=0)),
                ('paypal', models.URLField()),
                ('klarna', models.URLField()),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ID', models.IntegerField(default=0, unique=True)),
                ('product_name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='static/image')),
                ('category', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('quantity', models.CharField(max_length=16)),
                ('size', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Glasneaker.Product'),
        ),
    ]
