# Generated by Django 3.2.12 on 2022-03-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='品牌名')),
                ('views', models.IntegerField(default=0, verbose_name='关注')),
                ('likes', models.IntegerField(default=0, verbose_name='收藏')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'db_table': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoeid', models.CharField(max_length=128, verbose_name='鞋子款式')),
                ('shoessize', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='鞋码')),
                ('number', models.IntegerField(default=1, verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='单价')),
                ('user', models.CharField(max_length=128, verbose_name='用户')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'db_table': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='用户')),
                ('address', models.CharField(max_length=512, verbose_name='地址')),
                ('phonenumber', models.CharField(max_length=16, verbose_name='手机号')),
                ('ordernumber', models.CharField(max_length=512, verbose_name='订单号')),
                ('price', models.CharField(max_length=512, verbose_name='总价')),
                ('paypal', models.BooleanField(default=False, verbose_name='是否支付')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotionID', models.CharField(max_length=64, unique=True)),
                ('promotioncode', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '促销',
                'verbose_name_plural': '促销',
                'db_table': 'Promotion',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=64, verbose_name='商品名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('picture', models.CharField(max_length=128, verbose_name='图片')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='价格')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='库存')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Glasneaker.brand', verbose_name='品牌')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentnumber', models.IntegerField(default=0, verbose_name='品论数')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('reply', models.TextField(blank=True, verbose_name='回复')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Glasneaker.product')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'Comment',
            },
        ),
    ]
