# Generated by Django 2.1.5 on 2022-03-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glasneaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fisrt_name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
